import type { Flight, Drone } from './types';

export const mockFlights: Flight[] = [
  {
    id: 'UA2481',
    flightNumber: 'UA2481',
    airline: 'United Airlines',
    origin: 'SFO',
    destination: 'JFK',
    departureTime: '10:00 AM',
    arrivalTime: '6:00 PM',
    status: 'In-Flight',
    altitude: 35000,
    speed: 500,
    heading: 90,
    latitude: 39.8617,
    longitude: -104.6737,
  },
  {
    id: 'DL123',
    flightNumber: 'DL123',
    airline: 'Delta',
    origin: 'LAX',
    destination: 'ATL',
    departureTime: '11:30 AM',
    arrivalTime: '7:00 PM',
    status: 'In-Flight',
    altitude: 38000,
    speed: 550,
    heading: 110,
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 'AA456',
    flightNumber: 'AA456',
    airline: 'American Airlines',
    origin: 'ORD',
    destination: 'MIA',
    departureTime: '09:15 AM',
    arrivalTime: '1:30 PM',
    status: 'On Time',
    altitude: 0,
    speed: 0,
    heading: 0,
    latitude: 41.9742,
    longitude: -87.9073,
  },
    {
    id: 'SW789',
    flightNumber: 'SW789',
    airline: 'Southwest',
    origin: 'DEN',
    destination: 'LAS',
    departureTime: '2:00 PM',
    arrivalTime: '3:30 PM',
    status: 'Delayed',
    altitude: 0,
    speed: 0,
    heading: 0,
    latitude: 39.8617,
    longitude: -104.6737,
  },
];

export const mockDrones: Drone[] = [
  {
    id: 'DRN-001',
    operator: 'Amazon Prime Air',
    model: 'MK27-2',
    status: 'In-Flight',
    altitude: 300,
    speed: 40,
    latitude: 37.7749,
    longitude: -122.4194,
    battery: 82,
  },
  {
    id: 'DRN-002',
    operator: 'Wing',
    model: 'Hummingbird',
    status: 'In-Flight',
    altitude: 250,
    speed: 35,
    latitude: 37.7849,
    longitude: -122.4294,
    battery: 67,
  },
  {
    id: 'DRN-003',
    operator: 'Zipline',
    model: 'Platform 2',
    status: 'Grounded',
    altitude: 0,
    speed: 0,
    latitude: 37.7649,
    longitude: -122.4094,
    battery: 98,
  },
];

export const mockPassengerFlight = {
    flightNumber: "SN404",
    airline: "SkyNaptic Air",
    origin: {
        city: "San Francisco",
        code: "SFO",
    },
    destination: {
        city: "New York",
        code: "JFK",
        localTime: "4:30 PM",
        weather: "72°F Sunny",
    },
    status: "On Time",
    gate: "B12",
    seat: "14A",
    departure: {
        scheduled: "10:30 AM",
        estimated: "10:30 AM",
        terminal: "2",
    },
    arrival: {
        scheduled: "6:45 PM",
        estimated: "6:45 PM",
        terminal: "4",
    }
}

export const mockPilotFlightPlan = {
    flightNumber: "SN007",
    aircraft: "Boeing 787-9 Dreamliner",
    origin: "LHR",
    destination: "SIN",
    departureTime: "21:00Z",
    arrivalTime: "17:50Z",
    route: "LHR DCT DVR UL607 KOK GOLUM UZ904 KFA UN644 OTKEP L612 INBOM M770 REPSA N644 ADINA L510 PEPAS R460 VKR A464 IGREX/M083F390 A464 VPL DCT",
    altitude: "FL390",
    estimatedFuel: "95,000 kg",
    alternateAirport: "KUL"
}
